import mongoose from 'mongoose'
import { v4 as uuid } from 'uuid'

// A single notification delivered to one user. Notifications are generated by
// domain events (someone liked your post, staff hid your post, a welcome on
// first sign-in, broadcasts, etc.). The `message` is precomputed plain text so
// the feed can render without extra lookups; `link` points the user at the
// relevant in-app page.
const notificationSchema = new mongoose.Schema(
  {
    _id: { type: String, default: uuid },

    // Who receives this notification.
    recipientId: { type: String, required: true, ref: 'User', index: true },

    // What kind of event produced it.
    type: {
      type: String,
      required: true,
      enum: ['post_like', 'post_hidden', 'post_unhidden', 'welcome', 'announcement'],
    },

    // Who triggered it (null for system/announcement notifications).
    actorId: { type: String, default: null, ref: 'User' },
    actorName: { type: String, default: null }, // denormalised for cheap render

    // Optional related post.
    postId: { type: String, default: null, ref: 'Post' },

    // Precomputed, render-ready text + destination.
    message: { type: String, required: true, maxlength: 500 },
    link: { type: String, default: null },

    read: { type: Boolean, default: false, index: true },
  },
  { timestamps: { createdAt: true, updatedAt: false }, _id: false }
)

// Feed query: a recipient's notifications, newest first.
notificationSchema.index({ recipientId: 1, createdAt: -1 })
// Unread-count query.
notificationSchema.index({ recipientId: 1, read: 1 })
// Like-notification dedup (notifyPostLiked): runs on EVERY like to collapse
// repeats, so make it a precise lookup instead of scanning a user's feed.
notificationSchema.index({ recipientId: 1, postId: 1, actorId: 1, type: 1, read: 1 })

export const Notification = mongoose.model('Notification', notificationSchema)
